services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: vrd_scrapper
        restart: unless-stopped
        tty: true
        env_file:
            - .env
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
            - redis
        networks:
            - vrd_scrapper
        expose:
            - "9000"

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - vrd_scrapper

    mysql:
        image: mysql:8.3.0
        platform: linux/x86_64
        container_name: mysql
        restart: unless-stopped
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: vrd_scrapper
            MYSQL_USER: vrd_user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - vrd-scrapper_dbdata:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init-db.sql
        networks:
            - vrd_scrapper

    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - vrd_scrapper

    worker:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_worker
        depends_on:
            - app
        volumes:
            - ./:/var/www
        env_file:
            - .env
        command: php /var/www/artisan queue:work redis --sleep=3 --tries=3 --timeout=90
        restart: on-failure
        deploy:
            replicas: 10
            resources:
                limits:
                    cpus: '0.1'
                    memory: 100M
        networks:
            - vrd_scrapper

networks:
    vrd_scrapper:
        driver: bridge

volumes:
    esdata:
    vrd-scrapper_dbdata:
